# Generated by Django 3.1.3 on 2020-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=500)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
