# Generated by Django 3.1.3 on 2020-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('coursesectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=500)),
                ('instructorname', models.CharField(max_length=500)),
            ],
        ),
    ]
