# Generated by Django 3.1.3 on 2020-11-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0005_auto_20201123_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='lastname',
        ),
    ]
